[unix_http_server]
file=/tmp/supervisor.sock
chmod=0777
chown=root:{USER_NAME}

[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[include]
files = {BOOT_DIR}/system.conf.d/*.conf /etc/supervisor/conf.d/*.conf
