[program:cloudflared]
command=/usr/local/bin/cloudflared tunnel --no-autoupdate run --token %(ENV_CF_TOKEN)s
autostart=true
autorestart=true
stderr_logfile=/var/log/cloudflared.err.log
stdout_logfile=/var/log/cloudflared.out.log
