[program:easytier]
command=/usr/local/bin/easytier-core --network-name "{ET_NAME}" --network-secret "{ET_SECRET}" {ET_IPV4_ARG} {ET_PEERS_ARG} {ET_ARGS}
autostart=true
autorestart=true
stdout_logfile=/tmp/easytier.log
stderr_logfile=/tmp/easytier.err.log
