[program:{HP_PROC}]
command=/usr/local/bin/{HP_PROC} server -c {P2P_DIR}/config.yaml
autostart=true
autorestart=true
startsecs=3
stdout_logfile=/var/log/{HP_PROC}.out.log
stderr_logfile=/var/log/{HP_PROC}.err.log
