[program:{SB_PROC}]
command=/usr/local/bin/{SB_PROC} run -c {P2P_DIR}/sb-config.json
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/var/log/{SB_PROC}.out.log
stderr_logfile=/var/log/{SB_PROC}.err.log